language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-dash' ]; then cd .. && eval "mv $currentfolder generator-dash" && cd generator-dash; fi

